Repository backend-study-hammers/backend-study-assignments, pull requests merged in 2021-07, with the labels that each got.

#2 upload web2-css lecture
  web-jianny/web1-html/1.html
  web-jianny/web1-html/2.html
  web-jianny/web1-html/3.html
  web-jianny/web1-html/cat.jpg
  web-jianny/web1-html/index.html
  web-jianny/web2-css/1.html
  web-jianny/web2-css/2.html
  web-jianny/web2-css/3.html
  web-jianny/web2-css/box.html
  web-jianny/web2-css/cat.jpg
  web-jianny/web2-css/grid.html
  web-jianny/web2-css/index.html
  web-jianny/web2-css/mediaquery.html
  web-jianny/web2-css/style.css
Labels: 생활코딩, 수업 실습, 지안

#4 upload web2-js source code
  web-jianny/web2-js/1.html
  web-jianny/web2-js/2.html
  web-jianny/web2-js/3.html
  web-jianny/web2-js/box.html
  web-jianny/web2-js/cat.jpg
  web-jianny/web2-js/colors.js
  web-jianny/web2-js/ex1.html
  web-jianny/web2-js/ex2.html
  web-jianny/web2-js/ex3.html
  web-jianny/web2-js/ex4.html
  web-jianny/web2-js/ex5.html
  web-jianny/web2-js/grid.html
  web-jianny/web2-js/index.html
  web-jianny/web2-js/mediaquery.html
  web-jianny/web2-js/style.css
Labels: 생활코딩, 수업 실습, 지안

#7 upload google login & p5.js source code
  web-jianny/web3-login-google/1.html
  web-jianny/web3-login-google/2.html
  web-jianny/web3-login-google/3.html
  web-jianny/web3-login-google/box.html
  web-jianny/web3-login-google/cat.jpg
  web-jianny/web3-login-google/colors.js
  web-jianny/web3-login-google/grid.html
  web-jianny/web3-login-google/index.html
  web-jianny/web3-login-google/manualOauth.html
  web-jianny/web3-login-google/mediaquery.html
  web-jianny/web3-login-google/style.css
  web-jianny/web3-p5js/index.html
Labels: 생활코딩, 수업 실습, 지안

#9 폴더 정리
  web-binny/html,css,js/1.html
  web-binny/html,css,js/2.html
  web-binny/html,css,js/3.html
  web-binny/html,css,js/box.html
  web-binny/html,css,js/colors.js
  web-binny/html,css,js/ex1.html
  web-binny/html,css,js/ex10.html
  web-binny/html,css,js/ex2.html
  web-binny/html,css,js/ex4.html
  web-binny/html,css,js/grid.html
  web-binny/html,css,js/heedong.jpg
  web-binny/html,css,js/index.html
  web-binny/html,css,js/mediaquery.html
  web-binny/html,css,js/style.css
  web-binny/p5/index.html
Labels: 비니, 생활코딩, 수업 실습

#11 Jieuny-webfirst,webrecap폴더업로드
  web-jieuny/gangnam.html
  web-jieuny/webfirst/1.html
  web-jieuny/webfirst/2.html
  web-jieuny/webfirst/3.html
  web-jieuny/webfirst/coding.jpg
  web-jieuny/webfirst/ex10.html
  web-jieuny/webfirst/ex5.html
  web-jieuny/webfirst/ex7.html
  web-jieuny/webfirst/fetch.html
  web-jieuny/webfirst/grid.html
  web-jieuny/webfirst/index.html
  web-jieuny/webfirst/mideaquery.html
  web-jieuny/webrecap/colors.js
  web-jieuny/webrecap/euljiro.html
  web-jieuny/webrecap/ex1.html
  web-jieuny/webrecap/gangnam.html
  web-jieuny/webrecap/home.html
  web-jieuny/webrecap/jamsil.html
Labels: 생활코딩

#14 spring 입문 version 1
  binny/hello-spring 2/.gitignore
  binny/hello-spring 2/build.gradle
  binny/hello-spring 2/gradle/wrapper/gradle-wrapper.jar
  binny/hello-spring 2/gradle/wrapper/gradle-wrapper.properties
  binny/hello-spring 2/gradlew
  binny/hello-spring 2/gradlew.bat
  binny/hello-spring 2/settings.gradle
  binny/hello-spring 2/sql/ddl.sql
  binny/hello-spring 2/src/main/java/hello/hellospring/HelloSpringApplication.java
  binny/hello-spring 2/src/main/java/hello/hellospring/aop/TimeTraceAop.java
  binny/hello-spring 2/src/main/java/hello/hellospring/controller/HelloController.java
  binny/hello-spring 2/src/main/java/hello/hellospring/controller/HomeController.java
  binny/hello-spring 2/src/main/java/hello/hellospring/controller/MemberController.java
  binny/hello-spring 2/src/main/java/hello/hellospring/controller/MemberForm.java
  binny/hello-spring 2/src/main/java/hello/hellospring/domain/Member.java
  binny/hello-spring 2/src/main/java/hello/hellospring/repository/JdbcMemberRepository.java
  binny/hello-spring 2/src/main/java/hello/hellospring/repository/JdbcTemplateMemberRepository.java
  binny/hello-spring 2/src/main/java/hello/hellospring/repository/JpaMemberRepository.java
  binny/hello-spring 2/src/main/java/hello/hellospring/repository/MemberRepository.java
  binny/hello-spring 2/src/main/java/hello/hellospring/repository/MemoryMemberRepository.java
  binny/hello-spring 2/src/main/java/hello/hellospring/repository/SpringDataJpaMemberRepository.java
  binny/hello-spring 2/src/main/java/hello/hellospring/service/MemberService.java
  binny/hello-spring 2/src/main/java/hello/hellospring/service/SpringConfig.java
  binny/hello-spring 2/src/main/resources/application.properties
  binny/hello-spring 2/src/main/resources/static/hello-static.html
  binny/hello-spring 2/src/main/resources/static/index.html
  binny/hello-spring 2/src/main/resources/templates/hello-template.html
  binny/hello-spring 2/src/main/resources/templates/hello.html
  binny/hello-spring 2/src/main/resources/templates/home.html
  binny/hello-spring 2/src/main/resources/templates/members/createMemberForm.html
  binny/hello-spring 2/src/main/resources/templates/members/memberList.html
  binny/hello-spring 2/src/test/java/hello/hellospring/HelloSpringApplicationTests.java
  binny/hello-spring 2/src/test/java/hello/hellospring/repository/MemoryMemberRepositoryTest.java
  binny/hello-spring 2/src/test/java/hello/hellospring/service/MemberServiceIntegrationTest.java
  binny/hello-spring 2/src/test/java/hello/hellospring/service/MemberServiceTest.java
  binny/html,css,js/1.html
  binny/html,css,js/2.html
  binny/html,css,js/3.html
  binny/html,css,js/box.html
  binny/html,css,js/colors.js
  binny/html,css,js/ex1.html
  binny/html,css,js/ex10.html
  binny/html,css,js/ex2.html
  binny/html,css,js/ex4.html
  binny/html,css,js/grid.html
  binny/html,css,js/heedong.jpg
  binny/html,css,js/index.html
  binny/html,css,js/mediaquery.html
  binny/html,css,js/style.css
  binny/p5/index.html
Labels: spring, 비니, 수업 실습

#19 spring 입문 version 2
  binny/hello-spring 2nd/.gitignore
  binny/hello-spring 2nd/build.gradle
  binny/hello-spring 2nd/gradle/wrapper/gradle-wrapper.jar
  binny/hello-spring 2nd/gradle/wrapper/gradle-wrapper.properties
  binny/hello-spring 2nd/gradlew
  binny/hello-spring 2nd/gradlew.bat
  binny/hello-spring 2nd/settings.gradle
  binny/hello-spring 2nd/sql/ddl.sql
  binny/hello-spring 2nd/src/main/java/hello/hellospring/HelloSpringApplication.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/aop/TimeTraceAop.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/controller/HelloController.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/controller/HomeController.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/controller/MemberController.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/controller/MemberForm.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/domain/Member.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/repository/JdbcMemberRepository.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/repository/JdbcTemplateMemberRepository.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/repository/JpaMemberRepository.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/repository/MemberRepository.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/repository/MemoryMemberRepository.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/repository/SpringDataJpaMemberRepository.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/service/MemberService.java
  binny/hello-spring 2nd/src/main/java/hello/hellospring/service/SpringConfig.java
  binny/hello-spring 2nd/src/main/resources/application.properties
  binny/hello-spring 2nd/src/main/resources/static/hello-static.html
  binny/hello-spring 2nd/src/main/resources/static/index.html
  binny/hello-spring 2nd/src/main/resources/templates/hello-template.html
  binny/hello-spring 2nd/src/main/resources/templates/hello.html
  binny/hello-spring 2nd/src/main/resources/templates/home.html
  binny/hello-spring 2nd/src/main/resources/templates/members/createMemberForm.html
  binny/hello-spring 2nd/src/main/resources/templates/members/memberList.html
  binny/hello-spring 2nd/src/test/java/hello/hellospring/HelloSpringApplicationTests.java
  binny/hello-spring 2nd/src/test/java/hello/hellospring/repository/MemoryMemberRepositoryTest.java
  binny/hello-spring 2nd/src/test/java/hello/hellospring/service/MemberServiceIntegrationTest.java
  binny/hello-spring 2nd/src/test/java/hello/hellospring/service/MemberServiceTest.java
Labels: spring, 비니, 수업 실습

#21 Binny
  binny/core/.gitignore
  binny/core/build.gradle
  binny/core/gradle/wrapper/gradle-wrapper.jar
  binny/core/gradle/wrapper/gradle-wrapper.properties
  binny/core/gradlew
  binny/core/gradlew.bat
  binny/core/settings.gradle
  binny/core/src/main/java/hello/core/CoreApplication.java
  binny/core/src/main/java/hello/core/member/Grade.java
  binny/core/src/main/java/hello/core/member/Member.java
  binny/core/src/main/java/hello/core/member/MemberRepository.java
  binny/core/src/main/java/hello/core/member/MemberService.java
  binny/core/src/main/java/hello/core/member/MemberServiceImpl.java
  binny/core/src/main/java/hello/core/member/MemoryMemberRepository.java
  binny/core/src/main/resources/application.properties
  binny/core/src/test/java/hello/core/CoreApplicationTests.java
Labels: 비니, 수업 실습, 인프런

#23 Spring 기본 day2
  binny/core/src/main/java/hello/core/AppConfig.java
  binny/core/src/main/java/hello/core/MemberApp.java
  binny/core/src/main/java/hello/core/OrderApp.java
  binny/core/src/main/java/hello/core/discount/DiscountPolicy.java
  binny/core/src/main/java/hello/core/discount/FixDiscountPolicy.java
  binny/core/src/main/java/hello/core/discount/RateDiscountPolicy.java
  binny/core/src/main/java/hello/core/member/MemberServiceImpl.java
  binny/core/src/main/java/hello/core/order/Order.java
  binny/core/src/main/java/hello/core/order/OrderService.java
  binny/core/src/main/java/hello/core/order/OrderServiceImpl.java
  binny/core/src/test/java/hello/core/discount/RateDiscountPolicyTest.java
  binny/core/src/test/java/hello/core/member/MemberServiceTest.java
  binny/core/src/test/java/hello/core/order/OrderServiceTest.java
Labels: spring, 비니, 수업 실습

#25 스프링 기본편
  jieuny/core/.gitignore
  jieuny/core/build.gradle
  jieuny/core/gradle/wrapper/gradle-wrapper.jar
  jieuny/core/gradle/wrapper/gradle-wrapper.properties
  jieuny/core/gradlew
  jieuny/core/gradlew.bat
  jieuny/core/settings.gradle
  jieuny/core/src/main/java/hello/core/AppConfig.java
  jieuny/core/src/main/java/hello/core/CoreApplication.java
  jieuny/core/src/main/java/hello/core/MemberApp.java
  jieuny/core/src/main/java/hello/core/OrderApp.java
  jieuny/core/src/main/java/hello/core/discount/DiscountPolicy.java
  jieuny/core/src/main/java/hello/core/discount/Fixdiscountpolicy.java
  jieuny/core/src/main/java/hello/core/discount/RatediscountPolicy.java
  jieuny/core/src/main/java/hello/core/member/Grade.java
  jieuny/core/src/main/java/hello/core/member/Member.java
  jieuny/core/src/main/java/hello/core/member/MemberRepository.java
  jieuny/core/src/main/java/hello/core/member/MemberService.java
  jieuny/core/src/main/java/hello/core/member/MemberServiceImpl.java
  jieuny/core/src/main/java/hello/core/member/MemoryMemberRepository.java
  jieuny/core/src/main/java/hello/core/order/Order.java
  jieuny/core/src/main/java/hello/core/order/OrderService.java
  jieuny/core/src/main/java/hello/core/order/OrderServiceImpl.java
  jieuny/core/src/main/resources/appConfig.xml
  jieuny/core/src/main/resources/application.properties
  jieuny/core/src/test/java/hello/core/CoreApplicationTests.java
  jieuny/core/src/test/java/hello/core/beanfind/ApplicationContextBasicfindTest.java
  jieuny/core/src/test/java/hello/core/beanfind/ApplicationContextExtendsFindTest.java
  jieuny/core/src/test/java/hello/core/beanfind/ApplicationContextInfoTest.java
  jieuny/core/src/test/java/hello/core/beanfind/ApplicationContextSameBeanfindTest.java
  jieuny/core/src/test/java/hello/core/beanfind/xml/XmlAppContextTest.java
  jieuny/core/src/test/java/hello/core/discount/RatediscountPolicyTest.java
  jieuny/core/src/test/java/hello/core/member/MemberServiceImplTest.java
  jieuny/core/src/test/java/hello/core/order/OrderServiceTest.java
Labels: spring, 지으니

#26 Spring 기본 Day 3 code upload
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/AppConfig.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/AutoAppConfig.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/CoreApplication.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/discount/RateDiscountPolicy.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/member/MemberServiceImpl.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/member/MemoryMemberRepository.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/order/OrderServiceImpl.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/scan/AutoAppConfigTest.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/scan/filter/BeanA.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/scan/filter/BeanB.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/scan/filter/ComponentFilterAppConfigTest.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/scan/filter/MyExcludeComponent.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/scan/filter/MyIncludeComponent.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/singleton/ConfigurationSingletonTest.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/singleton/SingleTonTest.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/singleton/SingletonService.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/singleton/StatefulService.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/singleton/StatefulServiceTest.java
Labels: spring, 수업 실습, 인프런, 체리

#24 Spring Lecture Section 2
  jianny/SpringBoot/core/.gitignore
  jianny/SpringBoot/core/build.gradle
  jianny/SpringBoot/core/gradle/wrapper/gradle-wrapper.jar
  jianny/SpringBoot/core/gradle/wrapper/gradle-wrapper.properties
  jianny/SpringBoot/core/gradlew
  jianny/SpringBoot/core/gradlew.bat
  jianny/SpringBoot/core/settings.gradle
  jianny/SpringBoot/core/src/main/java/hello/core/CoreApplication.java
  jianny/SpringBoot/core/src/main/java/hello/core/MemberApp.java
  jianny/SpringBoot/core/src/main/java/hello/core/OrderApp.java
  jianny/SpringBoot/core/src/main/java/hello/core/discount/DiscountPolicy.java
  jianny/SpringBoot/core/src/main/java/hello/core/discount/FixDiscountPolicy.java
  jianny/SpringBoot/core/src/main/java/hello/core/member/Grade.java
  jianny/SpringBoot/core/src/main/java/hello/core/member/Member.java
  jianny/SpringBoot/core/src/main/java/hello/core/member/MemberRepository.java
  jianny/SpringBoot/core/src/main/java/hello/core/member/MemberService.java
  jianny/SpringBoot/core/src/main/java/hello/core/member/MemberServiceImpl.java
  jianny/SpringBoot/core/src/main/java/hello/core/member/MemoryMemberRepository.java
  jianny/SpringBoot/core/src/main/java/hello/core/order/Order.java
  jianny/SpringBoot/core/src/main/java/hello/core/order/OrderService.java
  jianny/SpringBoot/core/src/main/java/hello/core/order/OrderServiceImpl.java
  jianny/SpringBoot/core/src/main/resources/application.properties
  jianny/SpringBoot/core/src/test/java/hello/core/CoreApplicationTests.java
  jianny/SpringBoot/core/src/test/java/hello/core/member/MemberServiceTest.java
  jianny/SpringBoot/core/src/test/java/hello/core/order/OrderServiceTest.java
Labels: spring, 수업 실습, 인프런, 지안

#28 Spring 기본 day3
  binny/core/src/main/java/hello/core/AppConfig.java
  binny/core/src/main/java/hello/core/member/MemberServiceImpl.java
  binny/core/src/main/java/hello/core/order/OrderServiceImpl.java
  binny/core/src/main/resources/appConfig.xml
  binny/core/src/test/java/hello/core/beandefinition/BeanDefinitionTest.java
  binny/core/src/test/java/hello/core/beanfind/ApplicationContextBasicFindTest.java
  binny/core/src/test/java/hello/core/beanfind/ApplicationContextExtendsFindTest.java
  binny/core/src/test/java/hello/core/beanfind/ApplicationContextInfoTest.java
  binny/core/src/test/java/hello/core/beanfind/ApplicationContextSameBeanFindTest.java
  binny/core/src/test/java/hello/core/singletone/ConfigurationSingletoneTest.java
  binny/core/src/test/java/hello/core/singletone/SingletonTest.java
  binny/core/src/test/java/hello/core/singletone/SingletoneService.java
  binny/core/src/test/java/hello/core/singletone/StatefulService.java
  binny/core/src/test/java/hello/core/singletone/StatefulServiceTest.java
  binny/core/src/test/java/hello/core/xml/XmlAppContext.java
Labels: spring, 비니, 수업 실습

#27 Spring 기본 Day 4 code upload
  cherry/Spring-Boot.hello-spring/스프링 기본/core/build.gradle
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/AutoAppConfig.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/annotation/MainDiscountPolicy.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/discount/FixDiscountPolicy.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/discount/RateDiscountPolicy.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/main/java/hello/core/order/OrderServiceImpl.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/autowired/AutowiredTest.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/autowired/allbean/AllBeanTest.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/lifecycle/BeanLifeCycleTest.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/lifecycle/NetworkClient.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/order/OrderServiceImplTest.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/scope/PrototypeTest.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/scope/SingletonTest.java
  cherry/Spring-Boot.hello-spring/스프링 기본/core/src/test/java/hello/core/scope/SingletonWithPrototypeTest1.java
Labels: spring, 수업 실습, 인프런, 체리
